base.url.local=http://localhost:8080
base.url.dev=http://localhost:8080
base.url.test=http://localhost:8080
base.url.prod=http://localhost:8080

token.url.token.local=
token.url.token.dev=
token.url.token.test=
token.url.token.prod=

metrics-config-location.local=classpath:collector-metrics-config/local
metrics-config-location.dev=classpath:collector-metrics-config/dev
metrics-config-location.test=classpath:collector-metrics-config/test
metrics-config-location.prod=classpath:collector-metrics-config/prod

protocol=grpc
scan.all.classes=false