base.url.local=http://localhost:8080
base.url.dev=http://localhost:8080
base.url.test=http://localhost:8080
base.url.prod=http://localhost:8080

token.url.token.local=
token.url.token.dev=
token.url.token.test=
token.url.token.prod=

metrics-config-location.local=classpath:collector-metrics-config/local
metrics-config-location.dev=classpath:collector-metrics-config/dev
metrics-config-location.test=classpath:collector-metrics-config/test
metrics-config-location.prod=classpath:collector-metrics-config/prod

protocol.local=grpc
protocol.dev=grpc
protocol.test=http
protocol.prod=grpc

scan.all.classes.local=false
scan.all.classes.dev=true
scan.all.classes.test=false
scan.all.classes.prod=false

batch.size.local=0
batch.size.dev=20
batch.size.test=20
batch.size.prod=100