base.url.local=http://localhost:8080
base.url.dev=http://localhost:8080
base.url.test=http://localhost:8080
base.url.prod=http://localhost:8080

token.url.local=http://localhost:8080/auth/realms/accounts/protocol/openid-connect/token
token.url.dev=https://localhost:8080/auth/realms/accounts/protocol/openid-connect/token
token.url.test=https://localhost:8080/auth/realms/accounts/protocol/openid-connect/token
token.url.prod=https://inconfiguredUrl

metrics-config-location.local=classpath:imh-metrics-config/local
metrics-config-location.dev=classpath:imh-metrics-config/dev
metrics-config-location.test=classpath:imh-metrics-config/test
metrics-config-location.prod=classpath:imh-metrics-config/prod
